### ISSUE TITLE
menubar position has offset

### ISSUE THREAD

**Issue by awx-henry-liu** [foamzou/ITraffic-monitor-for-mac#9] opened 2023-03-16 07:43 UTC
<img width="358" alt="image" src="https://user-images.githubusercontent.com/79567572/225548184-79612d8f-c720-4258-87e7-c57ca4bb5b02.png">

<img width="242" alt="image" src="https://user-images.githubusercontent.com/79567572/225548263-3dc63ccf-daf9-4ab2-831d-76a60fede187.png">

**Comment by foamzou** [comment] 2023-03-17 02:11
duplicate of #8

**Closed by foamzou** 2023-03-17 02:11 UTC
